version: '2'
services:

  nginx:
    image: chang-rev-proxy
    container_name: chang-rev-proxy
    networks:
      - chang-rev-proxy
    ports:
      - 80:80

networks:
  chang-rev-proxy:
    external: true
